apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: jqlogs
spec:
  version: "${TAG}"
  homepage: https://github.com/shihyuho/kubectl-jqlogs
  shortDescription: Readable, colorful JSON logs via jq
  description: |
    Formats JSON logs from pods using a built-in jq processor. It behaves like
    "kubectl logs" but automatically detects and prettifies valid JSON lines.
    Non-JSON lines are printed as-is (Hybrid Processing). It supports all std
    kubectl logs flags mode, rich colors, and YAML output.
  caveats: |
    It uses a built-in gojq implementation, so no local jq is required.
  platforms:
    - selector:
        matchLabels:
          os: darwin
          arch: amd64
      uri: https://github.com/shihyuho/kubectl-jqlogs/releases/download/${TAG}/kubectl-jqlogs_Darwin_x86_64.tar.gz
      sha256: "${SHA256_DARWIN_AMD64}"
      bin: kubectl-jqlogs
    - selector:
        matchLabels:
          os: darwin
          arch: arm64
      uri: https://github.com/shihyuho/kubectl-jqlogs/releases/download/${TAG}/kubectl-jqlogs_Darwin_arm64.tar.gz
      sha256: "${SHA256_DARWIN_ARM64}"
      bin: kubectl-jqlogs
    - selector:
        matchLabels:
          os: linux
          arch: amd64
      uri: https://github.com/shihyuho/kubectl-jqlogs/releases/download/${TAG}/kubectl-jqlogs_Linux_x86_64.tar.gz
      sha256: "${SHA256_LINUX_AMD64}"
      bin: kubectl-jqlogs
    - selector:
        matchLabels:
          os: linux
          arch: arm64
      uri: https://github.com/shihyuho/kubectl-jqlogs/releases/download/${TAG}/kubectl-jqlogs_Linux_arm64.tar.gz
      sha256: "${SHA256_LINUX_ARM64}"
      bin: kubectl-jqlogs
    - selector:
        matchLabels:
          os: windows
          arch: amd64
      uri: https://github.com/shihyuho/kubectl-jqlogs/releases/download/${TAG}/kubectl-jqlogs_Windows_x86_64.zip
      sha256: "${SHA256_WINDOWS_AMD64}"
      bin: kubectl-jqlogs.exe
