name: Idea
description: Propose a new idea or improvement suggestion (not necessarily for immediate implementation).
title: "[IDEA] "
labels: ["idea"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your suggestion! We'd love to hear your thoughts.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe your idea in detail.
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Solved
      description: What problem does this idea solve? Or what benefits does it bring?
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Potential Solution
      description: (Optional) If you have preliminary thoughts on how to implement this, please describe here.
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any relevant references, inspiration sources, or screenshots.
    validations:
      required: false
